-- genre
INSERT INTO bds.genre (genre) VALUES ('Mystery');
INSERT INTO bds.genre (genre) VALUES ('Thriller');
INSERT INTO bds.genre (genre) VALUES ('Romance');
INSERT INTO bds.genre (genre) VALUES ('Science Fiction');
INSERT INTO bds.genre (genre) VALUES ('Fantasy');
INSERT INTO bds.genre (genre) VALUES ('Historical Fiction');
INSERT INTO bds.genre (genre) VALUES ('Horror');
INSERT INTO bds.genre (genre) VALUES ('Adventure');
INSERT INTO bds.genre (genre) VALUES ('Non-Fiction');
INSERT INTO bds.genre (genre) VALUES ('Biography');
INSERT INTO bds.genre (genre) VALUES ('Self-Help');
INSERT INTO bds.genre (genre) VALUES ('Young Adult');
INSERT INTO bds.genre (genre) VALUES ('Dystopian');
INSERT INTO bds.genre (genre) VALUES ('Historical Romance');
INSERT INTO bds.genre (genre) VALUES ('Humor');
INSERT INTO bds.genre (genre) VALUES ('Poetry');
INSERT INTO bds.genre (genre) VALUES ('Memoir');
INSERT INTO bds.genre (genre) VALUES ('Cookbook');
INSERT INTO bds.genre (genre) VALUES ('Travel');
INSERT INTO bds.genre (genre) VALUES ('Graphic Novel');

-- language
INSERT INTO bds.language (language) VALUES ('English');
INSERT INTO bds.language (language) VALUES ('Spanish');
INSERT INTO bds.language (language) VALUES ('French');
INSERT INTO bds.language (language) VALUES ('German');
INSERT INTO bds.language (language) VALUES ('Russian');
INSERT INTO bds.language (language) VALUES ('Dutch');
INSERT INTO bds.language (language) VALUES ('Greek');
INSERT INTO bds.language (language) VALUES ('Polish');
INSERT INTO bds.language (language) VALUES ('Hebrew');
INSERT INTO bds.language (language) VALUES ('Czech');
INSERT INTO bds.language (language) VALUES ('Slovak');

-- book_binding
INSERT INTO bds.book_binding (book_binding) VALUES ('Hardcover');
INSERT INTO bds.book_binding (book_binding) VALUES ('Softcover');
INSERT INTO bds.book_binding (book_binding) VALUES ('Spiral-bound');
INSERT INTO bds.book_binding (book_binding) VALUES ('Leatherbound');
INSERT INTO bds.book_binding (book_binding) VALUES ('Sewn');

-- literary_period
INSERT INTO bds.literary_period (literary_period) VALUES ('Ancient');
INSERT INTO bds.literary_period (literary_period) VALUES ('Medieval');
INSERT INTO bds.literary_period (literary_period) VALUES ('Renaissance');
INSERT INTO bds.literary_period (literary_period) VALUES ('Enlightenment');
INSERT INTO bds.literary_period (literary_period) VALUES ('Romanticism');
INSERT INTO bds.literary_period (literary_period) VALUES ('Victorian');
INSERT INTO bds.literary_period (literary_period) VALUES ('Realism');
INSERT INTO bds.literary_period (literary_period) VALUES ('Naturalism');
INSERT INTO bds.literary_period (literary_period) VALUES ('Modernism');
INSERT INTO bds.literary_period (literary_period) VALUES ('Postmodernism');
INSERT INTO bds.literary_period (literary_period) VALUES ('Contemporary');

-- book
INSERT INTO bds.book (ISBN, title, year_of_publication, evaluation, genre_id, language_id, book_binding_id, literary_period_id) VALUES ('978-580-066-374-1', 'The Enigma Chronicles', 1979, 6.35, 9, 8, 2, 6);
INSERT INTO bds.book (ISBN, title, year_of_publication, evaluation, genre_id, language_id, book_binding_id, literary_period_id) VALUES ('978-778-899-989-1', 'Serpents and Shadows', 1993, 2.94, 4, 10, 3, 9);
INSERT INTO bds.book (ISBN, title, year_of_publication, evaluation, genre_id, language_id, book_binding_id, literary_period_id) VALUES ('978-227-681-208-8', 'The Clockmaker''s Secret', 1935, 2.73, 7, 10, 1, 2);
INSERT INTO bds.book (ISBN, title, year_of_publication, evaluation, genre_id, language_id, book_binding_id, literary_period_id) VALUES ('978-939-780-673-9', 'Songs of the Siren', 1992, 9.69, 7, 11, 2, 1);
INSERT INTO bds.book (ISBN, title, year_of_publication, evaluation, genre_id, language_id, book_binding_id, literary_period_id) VALUES ('978-529-730-058-5', 'Harmony of the Cosmos', 1934, 4.86, 13, 9, 1, 11);
INSERT INTO bds.book (ISBN, title, year_of_publication, evaluation, genre_id, language_id, book_binding_id, literary_period_id) VALUES ('978-300-488-619-0', 'The Alchemist''s Daughter', 1979, 4.75, 6, 11, 1, 11);
INSERT INTO bds.book (ISBN, title, year_of_publication, evaluation, genre_id, language_id, book_binding_id, literary_period_id) VALUES ('978-759-111-029-7', 'Crimson Horizons', 1965, 5.84, 14, 7, 1, 4);
INSERT INTO bds.book (ISBN, title, year_of_publication, evaluation, genre_id, language_id, book_binding_id, literary_period_id) VALUES ('978-189-991-329-7', 'Crimson Horizons', 1965, 5.84, 14, 4, 4, 4);
INSERT INTO bds.book (ISBN, title, year_of_publication, evaluation, genre_id, language_id, book_binding_id, literary_period_id) VALUES ('978-910-288-819-9', 'The Quantum Paradox', 1933, 9.97, 5, 10, 1, 10);
INSERT INTO bds.book (ISBN, title, year_of_publication, evaluation, genre_id, language_id, book_binding_id, literary_period_id) VALUES ('978-486-239-652-0', 'Ghosts of the Machine', 2001, 1.66, 7, 9, 5, 2);
INSERT INTO bds.book (ISBN, title, year_of_publication, evaluation, genre_id, language_id, book_binding_id, literary_period_id) VALUES ('978-058-918-502-9', 'Chronicles of the Celestial', 1943, 7.1, 9, 7, 2, 2);
INSERT INTO bds.book (ISBN, title, year_of_publication, evaluation, genre_id, language_id, book_binding_id, literary_period_id) VALUES ('978-441-299-183-1', 'Ethereal Echoes', 1940, 2.16, 12, 10, 1, 6);
INSERT INTO bds.book (ISBN, title, year_of_publication, evaluation, genre_id, language_id, book_binding_id, literary_period_id) VALUES ('978-145-281-133-1', 'Ethereal Echoes', 1940, 2.16, 12, 10, 2, 6);
INSERT INTO bds.book (ISBN, title, year_of_publication, evaluation, genre_id, language_id, book_binding_id, literary_period_id) VALUES ('978-590-794-837-9', 'The Illusionist''s Dilemma', 1922, 9.73, 16, 1, 3, 2);
INSERT INTO bds.book (ISBN, title, year_of_publication, evaluation, genre_id, language_id, book_binding_id, literary_period_id) VALUES ('978-849-077-987-8', 'Sands of Eternity', 1987, 4.08, 4, 1, 2, 10);
INSERT INTO bds.book (ISBN, title, year_of_publication, evaluation, genre_id, language_id, book_binding_id, literary_period_id) VALUES ('978-989-050-839-3', 'The Last Oracle', 1975, 3.33, 2, 3, 1, 8);
INSERT INTO bds.book (ISBN, title, year_of_publication, evaluation, genre_id, language_id, book_binding_id, literary_period_id) VALUES ('978-741-835-650-7', 'Inferno of the Mind', 2014, 4.15, 19, 7, 5, 1);
INSERT INTO bds.book (ISBN, title, year_of_publication, evaluation, genre_id, language_id, book_binding_id, literary_period_id) VALUES ('978-439-182-102-3', 'The Cursed Kingdom', 1971, 3.57, 2, 2, 2, 11);
INSERT INTO bds.book (ISBN, title, year_of_publication, evaluation, genre_id, language_id, book_binding_id, literary_period_id) VALUES ('978-707-136-454-6', 'Stars Beyond the Veil', 1942, 8.78, 8, 5, 2, 2);
INSERT INTO bds.book (ISBN, title, year_of_publication, evaluation, genre_id, language_id, book_binding_id, literary_period_id) VALUES ('978-725-108-252-1', 'Beneath the Silver Moon', 1932, 4.63, 14, 10, 1, 5);
INSERT INTO bds.book (ISBN, title, year_of_publication, evaluation, genre_id, language_id, book_binding_id, literary_period_id) VALUES ('978-353-636-336-1', 'The Astral Traveler''s Guide', 1996, 5.6, 4, 10, 4, 8);
INSERT INTO bds.book (ISBN, title, year_of_publication, evaluation, genre_id, language_id, book_binding_id, literary_period_id) VALUES ('978-482-888-552-0', 'Labyrinth of Souls', 2014, 3.56, 13, 3, 2, 3);
INSERT INTO bds.book (ISBN, title, year_of_publication, evaluation, genre_id, language_id, book_binding_id, literary_period_id) VALUES ('978-708-113-555-6', 'Dreams of Another Realm', 1925, 2.82, 8, 1, 2, 11);
INSERT INTO bds.book (ISBN, title, year_of_publication, evaluation, genre_id, language_id, book_binding_id, literary_period_id) VALUES ('978-111-113-555-6', 'Dreams of Another Realm', 1925, 2.82, 8, 4, 4, 11);
INSERT INTO bds.book (ISBN, title, year_of_publication, evaluation, genre_id, language_id, book_binding_id, literary_period_id) VALUES ('978-865-087-862-0', 'Echoes from the Abyss', 1927, 6.37, 3, 8, 3, 4);
INSERT INTO bds.book (ISBN, title, year_of_publication, evaluation, genre_id, language_id, book_binding_id, literary_period_id) VALUES ('978-696-336-207-6', 'The Enchanted Labyrinth', 2015, 8.81, 7, 2, 2, 5);
INSERT INTO bds.book (ISBN, title, year_of_publication, evaluation, genre_id, language_id, book_binding_id, literary_period_id) VALUES ('978-836-826-249-4', 'Requiem for a Star', 2010, 6.12, 8, 11, 1, 3);
INSERT INTO bds.book (ISBN, title, year_of_publication, evaluation, genre_id, language_id, book_binding_id, literary_period_id) VALUES ('978-695-553-080-4', 'The Clockwork Constellations', 1944, 0.11, 1, 8, 3, 3);
INSERT INTO bds.book (ISBN, title, year_of_publication, evaluation, genre_id, language_id, book_binding_id, literary_period_id) VALUES ('978-731-876-000-4', 'Shadows of the Eternal', 1984, 2.02, 2, 7, 2, 11);
INSERT INTO bds.book (ISBN, title, year_of_publication, evaluation, genre_id, language_id, book_binding_id, literary_period_id) VALUES ('978-826-284-282-4', 'Specters of the Past', 1986, 4.29, 17, 3, 1, 1);
INSERT INTO bds.book (ISBN, title, year_of_publication, evaluation, genre_id, language_id, book_binding_id, literary_period_id) VALUES ('978-556-185-427-4', 'The Alchemy of Fate', 1969, 0.32, 15, 7, 2, 1);
INSERT INTO bds.book (ISBN, title, year_of_publication, evaluation, genre_id, language_id, book_binding_id, literary_period_id) VALUES ('978-459-167-969-3', 'The Oracle''s Prophecy', 1998, 9.2, 1, 11, 5, 10);
INSERT INTO bds.book (ISBN, title, year_of_publication, evaluation, genre_id, language_id, book_binding_id, literary_period_id) VALUES ('978-532-055-609-4', 'The Ethereal Nexus', 1998, 9.85, 6, 9, 1, 4);
INSERT INTO bds.book (ISBN, title, year_of_publication, evaluation, genre_id, language_id, book_binding_id, literary_period_id) VALUES ('978-968-702-004-2', 'Cogs and Ciphers', 1975, 1.53, 8, 7, 2, 9);
INSERT INTO bds.book (ISBN, title, year_of_publication, evaluation, genre_id, language_id, book_binding_id, literary_period_id) VALUES ('978-112-712-003-2', 'Cogs and Ciphers', 1975, 1.53, 8, 7, 1, 9);
INSERT INTO bds.book (ISBN, title, year_of_publication, evaluation, genre_id, language_id, book_binding_id, literary_period_id) VALUES ('978-114-718-009-2', 'Cogs and Ciphers', 1975, 1.53, 8, 1, 1, 9);
INSERT INTO bds.book (ISBN, title, year_of_publication, evaluation, genre_id, language_id, book_binding_id, literary_period_id) VALUES ('978-243-900-388-1', 'The Last Magician', 1955, 8.67, 9, 11, 2, 8);
INSERT INTO bds.book (ISBN, title, year_of_publication, evaluation, genre_id, language_id, book_binding_id, literary_period_id) VALUES ('978-647-168-714-1', 'The Quantum Conundrum', 1994, 0.19, 9, 9, 1, 6);
INSERT INTO bds.book (ISBN, title, year_of_publication, evaluation, genre_id, language_id, book_binding_id, literary_period_id) VALUES ('978-430-421-952-5', 'Visions of the Void', 1958, 2.87, 15, 3, 2, 11);
INSERT INTO bds.book (ISBN, title, year_of_publication, evaluation, genre_id, language_id, book_binding_id, literary_period_id) VALUES ('978-163-232-495-6', 'Sorcery and Stardust', 1964, 3.02, 3, 11, 2, 2);
INSERT INTO bds.book (ISBN, title, year_of_publication, evaluation, genre_id, language_id, book_binding_id, literary_period_id) VALUES ('978-686-407-361-4', 'The Enigmatic Empire', 2009, 6.0, 13, 1, 1, 10);
INSERT INTO bds.book (ISBN, title, year_of_publication, evaluation, genre_id, language_id, book_binding_id, literary_period_id) VALUES ('978-314-336-359-7', 'Beyond the Veil of Time', 1976, 4.08, 16, 8, 1, 11);
INSERT INTO bds.book (ISBN, title, year_of_publication, evaluation, genre_id, language_id, book_binding_id, literary_period_id) VALUES ('978-374-774-194-6', 'The Cosmic Kaleidoscope', 1949, 9.38, 13, 6, 4, 10);
INSERT INTO bds.book (ISBN, title, year_of_publication, evaluation, genre_id, language_id, book_binding_id, literary_period_id) VALUES ('978-996-240-705-9', 'The Arcane Archive', 2000, 3.58, 12, 11, 2, 5);
INSERT INTO bds.book (ISBN, title, year_of_publication, evaluation, genre_id, language_id, book_binding_id, literary_period_id) VALUES ('978-100-879-997-5', 'The Illusionist''s Mirage', 1988, 0.63, 8, 8, 1, 10);
INSERT INTO bds.book (ISBN, title, year_of_publication, evaluation, genre_id, language_id, book_binding_id, literary_period_id) VALUES ('978-572-098-250-6', 'Realm of the Lost Souls', 1976, 7.56, 13, 4, 1, 3);
INSERT INTO bds.book (ISBN, title, year_of_publication, evaluation, genre_id, language_id, book_binding_id, literary_period_id) VALUES ('978-629-786-637-9', 'The Celestial Codex', 1925, 0.48, 4, 7, 2, 2);
INSERT INTO bds.book (ISBN, title, year_of_publication, evaluation, genre_id, language_id, book_binding_id, literary_period_id) VALUES ('978-096-653-979-4', 'The Alchemist''s Legacy', 2016, 1.65, 8, 1, 2, 5);
INSERT INTO bds.book (ISBN, title, year_of_publication, evaluation, genre_id, language_id, book_binding_id, literary_period_id) VALUES ('978-854-444-089-3', 'Chronicles of the Nebula', 1938, 7.21, 18, 11, 2, 7);
INSERT INTO bds.book (ISBN, title, year_of_publication, evaluation, genre_id, language_id, book_binding_id, literary_period_id) VALUES ('978-926-356-323-2', 'Eclipse of the Mind', 2012, 6.74, 13, 4, 2, 2);
INSERT INTO bds.book (ISBN, title, year_of_publication, evaluation, genre_id, language_id, book_binding_id, literary_period_id) VALUES ('978-483-916-144-9', 'The Astral Alchemist', 1957, 9.2, 8, 10, 2, 2);
INSERT INTO bds.book (ISBN, title, year_of_publication, evaluation, genre_id, language_id, book_binding_id, literary_period_id) VALUES ('978-183-216-134-1', 'The Astral Alchemist', 1957, 9.2, 8, 1, 1, 2);
INSERT INTO bds.book (ISBN, title, year_of_publication, evaluation, genre_id, language_id, book_binding_id, literary_period_id) VALUES ('978-310-487-906-2', 'The Luminous Labyrinth', 1999, 2.13, 15, 4, 1, 3);
INSERT INTO bds.book (ISBN, title, year_of_publication, evaluation, genre_id, language_id, book_binding_id, literary_period_id) VALUES ('978-641-844-485-1', 'Spectral Serenity', 1956, 6.19, 11, 7, 2, 6);
INSERT INTO bds.book (ISBN, title, year_of_publication, evaluation, genre_id, language_id, book_binding_id, literary_period_id) VALUES ('978-043-402-254-3', 'Harmony of the Spheres', 2008, 7.01, 6, 7, 1, 6);
INSERT INTO bds.book (ISBN, title, year_of_publication, evaluation, genre_id, language_id, book_binding_id, literary_period_id) VALUES ('978-788-498-737-6', 'Songs of the Solar Winds', 1921, 4.77, 7, 1, 2, 8);
INSERT INTO bds.book (ISBN, title, year_of_publication, evaluation, genre_id, language_id, book_binding_id, literary_period_id) VALUES ('978-025-523-639-0', 'The Quantum Quandary', 1984, 2.19, 7, 5, 2, 11);
INSERT INTO bds.book (ISBN, title, year_of_publication, evaluation, genre_id, language_id, book_binding_id, literary_period_id) VALUES ('978-434-327-618-2', 'Ghosts of the Galactic Core', 1924, 0.62, 10, 5, 2, 8);
INSERT INTO bds.book (ISBN, title, year_of_publication, evaluation, genre_id, language_id, book_binding_id, literary_period_id) VALUES ('978-492-905-371-3', 'Echoes of Infinity', 1923, 2.28, 10, 1, 1, 6);
INSERT INTO bds.book (ISBN, title, year_of_publication, evaluation, genre_id, language_id, book_binding_id, literary_period_id) VALUES ('978-642-908-350-9', 'The Enchanted Echo', 2002, 5.23, 15, 1, 2, 4);
INSERT INTO bds.book (ISBN, title, year_of_publication, evaluation, genre_id, language_id, book_binding_id, literary_period_id) VALUES ('978-372-034-639-4', 'The Alchemy of Dreams', 1991, 1.23, 17, 6, 2, 5);
INSERT INTO bds.book (ISBN, title, year_of_publication, evaluation, genre_id, language_id, book_binding_id, literary_period_id) VALUES ('978-419-323-203-4', 'Chronicles of the Enigma', 1990, 1.22, 6, 10, 1, 1);
INSERT INTO bds.book (ISBN, title, year_of_publication, evaluation, genre_id, language_id, book_binding_id, literary_period_id) VALUES ('978-225-447-550-0', 'Memoirs of a Dreamer', 1985, 6.96, 5, 1, 1, 6);
INSERT INTO bds.book (ISBN, title, year_of_publication, evaluation, genre_id, language_id, book_binding_id, literary_period_id) VALUES ('978-198-542-160-0', 'Memoirs of a Dreamer', 1985, 6.96, 5, 2, 1, 6);
INSERT INTO bds.book (ISBN, title, year_of_publication, evaluation, genre_id, language_id, book_binding_id, literary_period_id) VALUES ('978-902-812-626-8', 'Journey to Self: A Memoir', 1924, 0.69, 18, 9, 2, 1);
INSERT INTO bds.book (ISBN, title, year_of_publication, evaluation, genre_id, language_id, book_binding_id, literary_period_id) VALUES ('978-892-189-858-3', 'Whispers of My Soul', 2007, 3.59, 20, 11, 1, 7);
INSERT INTO bds.book (ISBN, title, year_of_publication, evaluation, genre_id, language_id, book_binding_id, literary_period_id) VALUES ('978-708-891-441-7', 'Chasing Dreams: My Life Story', 1948, 7.17, 19, 4, 2, 6);

-- author
INSERT INTO bds.author (first_name, last_name, date_of_birth, date_of_death, language_id) VALUES ('John', 'Hill', '1918-09-15', '1977-05-16', 4);
INSERT INTO bds.author (first_name, last_name, date_of_birth, date_of_death, language_id) VALUES ('James', 'Hall', '1983-07-25', '2022-02-28', 8);
INSERT INTO bds.author (first_name, last_name, date_of_birth, date_of_death, language_id) VALUES ('Ava', 'Brown', '1952-12-07', '2021-11-10', 6);
INSERT INTO bds.author (first_name, last_name, date_of_birth, date_of_death, language_id) VALUES ('Benjamin', 'Brown', '1908-05-02', '1975-09-15', 5);
INSERT INTO bds.author (first_name, last_name, date_of_birth, date_of_death, language_id) VALUES ('Michael', 'Johnson', '1936-06-12', '1967-06-05', 1);
INSERT INTO bds.author (first_name, last_name, date_of_birth, date_of_death, language_id) VALUES ('Ava', 'Lee', '2001-10-10', null, 11);
INSERT INTO bds.author (first_name, last_name, date_of_birth, date_of_death, language_id) VALUES ('William', 'Adams', '1988-04-01', null, 2);
INSERT INTO bds.author (first_name, last_name, date_of_birth, date_of_death, language_id) VALUES ('William', 'Young', '1941-08-17', '1987-09-19', 9);
INSERT INTO bds.author (first_name, last_name, date_of_birth, date_of_death, language_id) VALUES ('William', 'Clark', '1976-08-21', '2011-12-18', 1);
INSERT INTO bds.author (first_name, last_name, date_of_birth, date_of_death, language_id) VALUES ('Emma', 'Adams', '1993-10-18', null, 7);
INSERT INTO bds.author (first_name, last_name, date_of_birth, date_of_death, language_id) VALUES ('Liam', 'Lewis', '1986-09-06', '2020-11-08', 1);
INSERT INTO bds.author (first_name, last_name, date_of_birth, date_of_death, language_id) VALUES ('Liam', 'Johnson', '1952-09-14', '1973-08-20', 6);
INSERT INTO bds.author (first_name, last_name, date_of_birth, date_of_death, language_id) VALUES ('Olivia', 'Clark', '1948-01-11', '2012-07-17', 9);
INSERT INTO bds.author (first_name, last_name, date_of_birth, date_of_death, language_id) VALUES ('Alice', 'Lee', '1951-05-26', '1993-06-28', 2);
INSERT INTO bds.author (first_name, last_name, date_of_birth, date_of_death, language_id) VALUES ('Emma', 'Clark', '1930-12-17', '1969-01-11', 11);
INSERT INTO bds.author (first_name, last_name, date_of_birth, date_of_death, language_id) VALUES ('Olivia', 'Hall', '1990-06-21', null, 7);
INSERT INTO bds.author (first_name, last_name, date_of_birth, date_of_death, language_id) VALUES ('William', 'Young', '1966-10-04', null, 7);
INSERT INTO bds.author (first_name, last_name, date_of_birth, date_of_death, language_id) VALUES ('Ava', 'Brown', '1992-05-07', null, 8);
INSERT INTO bds.author (first_name, last_name, date_of_birth, date_of_death, language_id) VALUES ('Olivia', 'Lee', '2004-05-17', null, 5);
INSERT INTO bds.author (first_name, last_name, date_of_birth, date_of_death, language_id) VALUES ('Sophia', 'Taylor', '1986-12-03', null, 5);
INSERT INTO bds.author (first_name, last_name, date_of_birth, date_of_death, language_id) VALUES ('Ava', 'Adams', '1912-06-20', '1942-11-06', 11);
INSERT INTO bds.author (first_name, last_name, date_of_birth, date_of_death, language_id) VALUES ('Michael', 'Johnson', '1956-02-11', '2023-05-14', 5);
INSERT INTO bds.author (first_name, last_name, date_of_birth, date_of_death, language_id) VALUES ('Liam', 'Adams', '1976-06-20', '1999-02-26', 9);
INSERT INTO bds.author (first_name, last_name, date_of_birth, date_of_death, language_id) VALUES ('Benjamin', 'Lewis', '1987-06-27', '2003-04-09', 2);
INSERT INTO bds.author (first_name, last_name, date_of_birth, date_of_death, language_id) VALUES ('Sophia', 'Lee', '1927-11-17', '1954-07-17', 1);
INSERT INTO bds.author (first_name, last_name, date_of_birth, date_of_death, language_id) VALUES ('Sophia', 'Adams', '1970-06-23', '2002-11-03', 1);
INSERT INTO bds.author (first_name, last_name, date_of_birth, date_of_death, language_id) VALUES ('Alice', 'Clark', '1997-04-06', null, 1);
INSERT INTO bds.author (first_name, last_name, date_of_birth, date_of_death, language_id) VALUES ('Emma', 'Hill', '1941-11-07', '1962-09-29', 9);
INSERT INTO bds.author (first_name, last_name, date_of_birth, date_of_death, language_id) VALUES ('Alice', 'Smith', '1985-07-03', null, 7);
INSERT INTO bds.author (first_name, last_name, date_of_birth, date_of_death, language_id) VALUES ('James', 'Lewis', '1969-08-15', '1997-03-03', 7);
INSERT INTO bds.author (first_name, last_name, date_of_birth, date_of_death, language_id) VALUES ('James', 'Hall', '1903-02-07', '1933-07-07', 6);
INSERT INTO bds.author (first_name, last_name, date_of_birth, date_of_death, language_id) VALUES ('James', 'Lee', '1956-10-25', '1981-02-25', 3);
INSERT INTO bds.author (first_name, last_name, date_of_birth, date_of_death, language_id) VALUES ('Emma', 'Adams', '1941-02-26', '2008-10-22', 2);
INSERT INTO bds.author (first_name, last_name, date_of_birth, date_of_death, language_id) VALUES ('Olivia', 'Hall', '1967-04-18', null, 11);
INSERT INTO bds.author (first_name, last_name, date_of_birth, date_of_death, language_id) VALUES ('Emma', 'Lee', '1928-01-23', '1954-02-02', 7);

-- book_has_author
INSERT INTO bds.book_has_author (book_id, author_id) VALUES (1, 3);
INSERT INTO bds.book_has_author (book_id, author_id) VALUES (2, 2);
INSERT INTO bds.book_has_author (book_id, author_id) VALUES (3, 4);
INSERT INTO bds.book_has_author (book_id, author_id) VALUES (4, 13);
INSERT INTO bds.book_has_author (book_id, author_id) VALUES (5, 1);
INSERT INTO bds.book_has_author (book_id, author_id) VALUES (6, 13);
INSERT INTO bds.book_has_author (book_id, author_id) VALUES (7, 33);
INSERT INTO bds.book_has_author (book_id, author_id) VALUES (8, 33);
INSERT INTO bds.book_has_author (book_id, author_id) VALUES (9, 31);
INSERT INTO bds.book_has_author (book_id, author_id) VALUES (10, 26);
INSERT INTO bds.book_has_author (book_id, author_id) VALUES (11, 35);
INSERT INTO bds.book_has_author (book_id, author_id) VALUES (12, 35);
INSERT INTO bds.book_has_author (book_id, author_id) VALUES (13, 35);
INSERT INTO bds.book_has_author (book_id, author_id) VALUES (14, 21);
INSERT INTO bds.book_has_author (book_id, author_id) VALUES (15, 14);
INSERT INTO bds.book_has_author (book_id, author_id) VALUES (16, 14);
INSERT INTO bds.book_has_author (book_id, author_id) VALUES (17, 11);
INSERT INTO bds.book_has_author (book_id, author_id) VALUES (18, 25);
INSERT INTO bds.book_has_author (book_id, author_id) VALUES (19, 25);
INSERT INTO bds.book_has_author (book_id, author_id) VALUES (20, 21);
INSERT INTO bds.book_has_author (book_id, author_id) VALUES (21, 9);
INSERT INTO bds.book_has_author (book_id, author_id) VALUES (22, 7);
INSERT INTO bds.book_has_author (book_id, author_id) VALUES (22, 16);
INSERT INTO bds.book_has_author (book_id, author_id) VALUES (23, 31);
INSERT INTO bds.book_has_author (book_id, author_id) VALUES (24, 31);
INSERT INTO bds.book_has_author (book_id, author_id) VALUES (25, 4);
INSERT INTO bds.book_has_author (book_id, author_id) VALUES (26, 34);
INSERT INTO bds.book_has_author (book_id, author_id) VALUES (26, 16);
INSERT INTO bds.book_has_author (book_id, author_id) VALUES (27, 18);
INSERT INTO bds.book_has_author (book_id, author_id) VALUES (27, 16);
INSERT INTO bds.book_has_author (book_id, author_id) VALUES (27, 29);
INSERT INTO bds.book_has_author (book_id, author_id) VALUES (28, 15);
INSERT INTO bds.book_has_author (book_id, author_id) VALUES (29, 17);
INSERT INTO bds.book_has_author (book_id, author_id) VALUES (30, 17);
INSERT INTO bds.book_has_author (book_id, author_id) VALUES (31, 22);
INSERT INTO bds.book_has_author (book_id, author_id) VALUES (32, 22);
INSERT INTO bds.book_has_author (book_id, author_id) VALUES (32, 23);
INSERT INTO bds.book_has_author (book_id, author_id) VALUES (33, 22);
INSERT INTO bds.book_has_author (book_id, author_id) VALUES (33, 23);
INSERT INTO bds.book_has_author (book_id, author_id) VALUES (34, 5);
INSERT INTO bds.book_has_author (book_id, author_id) VALUES (34, 32);
INSERT INTO bds.book_has_author (book_id, author_id) VALUES (35, 5);
INSERT INTO bds.book_has_author (book_id, author_id) VALUES (35, 32);
INSERT INTO bds.book_has_author (book_id, author_id) VALUES (36, 5);
INSERT INTO bds.book_has_author (book_id, author_id) VALUES (36, 32);
INSERT INTO bds.book_has_author (book_id, author_id) VALUES (37, 15);
INSERT INTO bds.book_has_author (book_id, author_id) VALUES (38, 34);
INSERT INTO bds.book_has_author (book_id, author_id) VALUES (39, 8);
INSERT INTO bds.book_has_author (book_id, author_id) VALUES (40, 13);
INSERT INTO bds.book_has_author (book_id, author_id) VALUES (41, 10);
INSERT INTO bds.book_has_author (book_id, author_id) VALUES (41, 29);
INSERT INTO bds.book_has_author (book_id, author_id) VALUES (42, 14);
INSERT INTO bds.book_has_author (book_id, author_id) VALUES (43, 4);
INSERT INTO bds.book_has_author (book_id, author_id) VALUES (44, 20);
INSERT INTO bds.book_has_author (book_id, author_id) VALUES (45, 17);
INSERT INTO bds.book_has_author (book_id, author_id) VALUES (46, 28);
INSERT INTO bds.book_has_author (book_id, author_id) VALUES (47, 31);
INSERT INTO bds.book_has_author (book_id, author_id) VALUES (48, 19);
INSERT INTO bds.book_has_author (book_id, author_id) VALUES (49, 4);
INSERT INTO bds.book_has_author (book_id, author_id) VALUES (50, 24);
INSERT INTO bds.book_has_author (book_id, author_id) VALUES (50, 27);
INSERT INTO bds.book_has_author (book_id, author_id) VALUES (51, 1);
INSERT INTO bds.book_has_author (book_id, author_id) VALUES (52, 1);
INSERT INTO bds.book_has_author (book_id, author_id) VALUES (53, 30);
INSERT INTO bds.book_has_author (book_id, author_id) VALUES (54, 5);
INSERT INTO bds.book_has_author (book_id, author_id) VALUES (55, 7);
INSERT INTO bds.book_has_author (book_id, author_id) VALUES (55, 18);
INSERT INTO bds.book_has_author (book_id, author_id) VALUES (56, 31);
INSERT INTO bds.book_has_author (book_id, author_id) VALUES (57, 12);
INSERT INTO bds.book_has_author (book_id, author_id) VALUES (58, 31);
INSERT INTO bds.book_has_author (book_id, author_id) VALUES (59, 31);
INSERT INTO bds.book_has_author (book_id, author_id) VALUES (60, 2);
INSERT INTO bds.book_has_author (book_id, author_id) VALUES (61, 26);
INSERT INTO bds.book_has_author (book_id, author_id) VALUES (62, 26);
INSERT INTO bds.book_has_author (book_id, author_id) VALUES (63, 8);
INSERT INTO bds.book_has_author (book_id, author_id) VALUES (64, 8);
INSERT INTO bds.book_has_author (book_id, author_id) VALUES (65, 31);
INSERT INTO bds.book_has_author (book_id, author_id) VALUES (66, 17);
INSERT INTO bds.book_has_author (book_id, author_id) VALUES (66, 29);
INSERT INTO bds.book_has_author (book_id, author_id) VALUES (67, 25);

-- city
INSERT INTO bds.city (city) VALUES ('Chicago');
INSERT INTO bds.city (city) VALUES ('Phoenix');
INSERT INTO bds.city (city) VALUES ('Philadelphia');
INSERT INTO bds.city (city) VALUES ('Boston');
INSERT INTO bds.city (city) VALUES ('Atlanta');

-- address
INSERT INTO bds.address (street, house_num, city_id) VALUES ('Maplewood Avenue', 245, 1);
INSERT INTO bds.address (street, house_num, city_id) VALUES ('Oakridge Drive', 23, 1);
INSERT INTO bds.address (street, house_num, city_id) VALUES ('Greenwood Street', 127, 2);
INSERT INTO bds.address (street, house_num, city_id) VALUES ('Magnolia Avenue', 89, 2);
INSERT INTO bds.address (street, house_num, city_id) VALUES ('Redwood Drive', 158, 2);
INSERT INTO bds.address (street, house_num, city_id) VALUES ('Willow Street', 45, 1);
INSERT INTO bds.address (street, house_num, city_id) VALUES ('Sycamore Lane', 39, 3);
INSERT INTO bds.address (street, house_num, city_id) VALUES ('Cedar Street', 192, 4);
INSERT INTO bds.address (street, house_num, city_id) VALUES ('Rustic Road', 5, 3);
INSERT INTO bds.address (street, house_num, city_id) VALUES ('Heritage Lane', 1, 3);
INSERT INTO bds.address (street, house_num, city_id) VALUES ('Riverview Avenue', 201, 5);
INSERT INTO bds.address (street, house_num, city_id) VALUES ('Goldenrod Street', 230, 2);

-- library
INSERT INTO bds.library (name, address_id) VALUES ('Chapter & Verse', 1);
INSERT INTO bds.library (name, address_id) VALUES ('Knowledge Hub', 2);
INSERT INTO bds.library (name, address_id) VALUES ('Book Nook', 3);
INSERT INTO bds.library (name, address_id) VALUES ('Reading Haven', 4);
INSERT INTO bds.library (name, address_id) VALUES ('The Bookshelf', 5);
INSERT INTO bds.library (name, address_id) VALUES ('Whimsical Words', 6);
INSERT INTO bds.library (name, address_id) VALUES ('Storyteller''s Den', 7);
INSERT INTO bds.library (name, address_id) VALUES ('Page Turner', 8);
INSERT INTO bds.library (name, address_id) VALUES ('Word Weavers', 9);
INSERT INTO bds.library (name, address_id) VALUES ('Literary Corner', 10);
INSERT INTO bds.library (name, address_id) VALUES ('Readers', 11);
INSERT INTO bds.library (name, address_id) VALUES ('Book Oasis', 12);

-- physical_book
INSERT INTO bds.physical_book (state, book_id, library_id) VALUES ('No visible defects', 1, null);
INSERT INTO bds.physical_book (state, book_id, library_id) VALUES ('Like New', 2, 2);
INSERT INTO bds.physical_book (book_id, library_id) VALUES (3, 3);
INSERT INTO bds.physical_book (book_id, library_id) VALUES (4, 4);
INSERT INTO bds.physical_book (state, book_id, library_id) VALUES ('Slight wear on cover', 5, 5);
INSERT INTO bds.physical_book (book_id, library_id) VALUES (5, 7);
INSERT INTO bds.physical_book (state, book_id, library_id) VALUES ('Good, minor creases', 6, 8);
INSERT INTO bds.physical_book (state, book_id, library_id) VALUES ('Moderate wear, some markings', 7, 9);
INSERT INTO bds.physical_book (state, book_id, library_id) VALUES ('Readable, noticeable wear', 8, 9);
INSERT INTO bds.physical_book (book_id, library_id) VALUES (8, null);
INSERT INTO bds.physical_book (state, book_id, library_id) VALUES ('Readable with significant wear', 9, 10);
INSERT INTO bds.physical_book (state, book_id, library_id) VALUES ('Fragile, loose pages', 10, 11);
INSERT INTO bds.physical_book (book_id, library_id) VALUES (11, 11);
INSERT INTO bds.physical_book (state, book_id, library_id) VALUES ('Frayed edges, loose binding', 12, 9);
INSERT INTO bds.physical_book (state, book_id, library_id) VALUES ('Stained pages, torn cover', 13, 10);
INSERT INTO bds.physical_book (book_id, library_id) VALUES (13, 3);
INSERT INTO bds.physical_book (book_id, library_id) VALUES (14, 12);
INSERT INTO bds.physical_book (state, book_id, library_id) VALUES ('Water-damaged, pages stuck together', 15, 11);
INSERT INTO bds.physical_book (state, book_id, library_id) VALUES ('Ripped pages, cover missing', 16, 12);
INSERT INTO bds.physical_book (book_id, library_id) VALUES (17, 4);
INSERT INTO bds.physical_book (book_id, library_id) VALUES (18, 1);
INSERT INTO bds.physical_book (state, book_id, library_id) VALUES ('No signs of wear, pristine condition', 19, 2);
INSERT INTO bds.physical_book (state, book_id, library_id) VALUES ('Like New', 20, 7);
INSERT INTO bds.physical_book (state, book_id, library_id) VALUES ('Slight creases', 21, 3);
INSERT INTO bds.physical_book (state, book_id, library_id) VALUES ('Minimal wear, well-maintained', 22, 4);
INSERT INTO bds.physical_book (state, book_id, library_id) VALUES ('Visible wear, intact binding', 23, 5);
INSERT INTO bds.physical_book (state, book_id, library_id) VALUES ('Readable, minor markings', 24, 6);
INSERT INTO bds.physical_book (state, book_id, library_id) VALUES ('New', 23, 7);
INSERT INTO bds.physical_book (state, book_id, library_id) VALUES ('Well-used, dog-eared pages', 25, 6);
INSERT INTO bds.physical_book (state, book_id, library_id) VALUES ('Significant wear, taped cover', 26, 9);
INSERT INTO bds.physical_book (book_id, library_id) VALUES (27, null);
INSERT INTO bds.physical_book (state, book_id, library_id) VALUES ('Heavily worn, but readable', 28, 11);
INSERT INTO bds.physical_book (state, book_id, library_id) VALUES ('Torn pages, taped binding', 29, 10);
INSERT INTO bds.physical_book (state, book_id, library_id) VALUES ('Spine missing, fragile', 30, null);
INSERT INTO bds.physical_book (state, book_id, library_id) VALUES ('Severe water damage, illegible', 31, 6);
INSERT INTO bds.physical_book (state, book_id, library_id) VALUES ('Like New', 32, 1);
INSERT INTO bds.physical_book (state, book_id, library_id) VALUES ('Like New', 33, 7);
INSERT INTO bds.physical_book (book_id, library_id) VALUES (34, 4);
INSERT INTO bds.physical_book (state, book_id, library_id) VALUES ('Minimal wear, well-maintained', 35, 4);
INSERT INTO bds.physical_book (state, book_id, library_id) VALUES ('Visible wear, intact binding', 36, 5);
INSERT INTO bds.physical_book (book_id, library_id) VALUES (36, 10);
INSERT INTO bds.physical_book (book_id, library_id) VALUES (36, 7);
INSERT INTO bds.physical_book (state, book_id, library_id) VALUES ('Readable, minor markings', 37, 9);
INSERT INTO bds.physical_book (state, book_id, library_id) VALUES ('Well-used, dog-eared pages', 38, 7);
INSERT INTO bds.physical_book (book_id, library_id) VALUES (39, 3);
INSERT INTO bds.physical_book (state, book_id, library_id) VALUES ('Significant wear, taped cover', 40, 8);
INSERT INTO bds.physical_book (state, book_id, library_id) VALUES ('Heavily worn, but readable', 41, 9);
INSERT INTO bds.physical_book (state, book_id, library_id) VALUES ('Torn pages, taped binding', 42, 10);
INSERT INTO bds.physical_book (book_id, library_id) VALUES (42, 6);
INSERT INTO bds.physical_book (book_id, library_id) VALUES (42, 3);
INSERT INTO bds.physical_book (state, book_id, library_id) VALUES ('Spine missing, fragile', 43, 11);
INSERT INTO bds.physical_book (book_id, library_id) VALUES (44, 5);
INSERT INTO bds.physical_book (state, book_id, library_id) VALUES ('Severe water damage, illegible', 45, 12);
INSERT INTO bds.physical_book (state, book_id, library_id) VALUES ('Like New', 46, 1);
INSERT INTO bds.physical_book (state, book_id, library_id) VALUES ('Mint condition, as good as new', 47, 8);
INSERT INTO bds.physical_book (state, book_id, library_id) VALUES ('Slight wear, no visible marks', 48, 1);
INSERT INTO bds.physical_book (state, book_id, library_id) VALUES ('Minor creases', 49, 2);
INSERT INTO bds.physical_book (state, book_id, library_id) VALUES ('Readable, moderate wear', 50, 5);
INSERT INTO bds.physical_book (state, book_id, library_id) VALUES ('Visible wear, intact pages', 51, 6);
INSERT INTO bds.physical_book (state, book_id, library_id) VALUES ('Significant wear, but functional', 52, 7);
INSERT INTO bds.physical_book (state, book_id, library_id) VALUES ('Heavily used, taped cover', 53, 8);
INSERT INTO bds.physical_book (state, book_id, library_id) VALUES ('Yellowed pages', 54, 9);
INSERT INTO bds.physical_book (state, book_id, library_id) VALUES ('Fragile', 55, 10);

-- role
INSERT INTO bds.role (role) VALUES ('administrator');
INSERT INTO bds.role (role) VALUES ('student');
INSERT INTO bds.role (role) VALUES ('basic');
INSERT INTO bds.role (role) VALUES ('librarian');
INSERT INTO bds.role (role) VALUES ('child');

-- user
INSERT INTO bds.user (first_name, last_name, username, date_of_birth, password_hash, role_id) VALUES ('John', 'Doe', 'johndoe123', '1990-05-15', '$argon2id$v=19$m=65536,t=10,p=1$DoTKKk6y2TWhf1Smb0KXMA$jjZHU+NvtuE7+FkSKvuuJvej0V4r8sAMvyMS09crm2s', 3);
INSERT INTO bds.user (first_name, last_name, username, date_of_birth, password_hash, role_id) VALUES ('Alice', 'Smith', 'alicesmith456', '1985-08-23', '$argon2id$v=19$m=65536,t=10,p=1$eL880Lie0ey9mzC/XdXPvw$EyHJ2mvm0VgFdBYofWzyesXAYXCqUWsrHHL64VRCp5k', 2);
INSERT INTO bds.user (first_name, last_name, username, date_of_birth, password_hash, role_id) VALUES ('Michael', 'Johnson', 'mikejohnson789', '1992-02-10', '$argon2id$v=19$m=65536,t=10,p=1$r5BCwxmJfvSNh20BEKbRCQ$Qitnf6J4FeHHzP6gI5Fn7KZCt+G8R/q00jlVSIb7bOo', 2);
INSERT INTO bds.user (first_name, last_name, username, date_of_birth, password_hash, role_id) VALUES ('Emma', 'Williams', 'emmaw123', '1988-11-30', '$argon2id$v=19$m=65536,t=10,p=1$DtrvYmxk1d6kHHkXg09Zxg$ECHcHaZv0n2tALHFZSVj9Vua09Up1z+hcBUxZCXV8OU', 3);
INSERT INTO bds.user (first_name, last_name, username, date_of_birth, password_hash, role_id) VALUES ('William', 'Brown', 'will.brown', '1995-04-18', '$argon2id$v=19$m=65536,t=10,p=1$S1aTfd8gZhUfT+c5lhC2gQ$1Weog/JgQ9jNroNwWXsOFhxKh2Gs1zSHChxTX6lmNZA', 3);
INSERT INTO bds.user (first_name, last_name, username, date_of_birth, password_hash, role_id) VALUES ('Ethan', 'Davis', 'ethand', '1987-09-12', '$argon2id$v=19$m=65536,t=10,p=1$6GfBlTEPfKv8iZc6TX4lqw$RfxvTR6ketz/S1KttXE9YCnE5A2zx6MWe1Qnf8zEXAU', 2);
INSERT INTO bds.user (first_name, last_name, username, date_of_birth, password_hash, role_id) VALUES ('Olivia', 'Lee', 'olivialee', '1993-03-25', '$argon2id$v=19$m=65536,t=10,p=1$MPMhXQGFWYeOrwvhdF7G5g$00jyI3F42+vzAMtbPkN4mi1YV3oShC7EIBUIbLfsh2Y', 3);
INSERT INTO bds.user (first_name, last_name, username, date_of_birth, password_hash, role_id) VALUES ('Liam', 'Anderson', 'liamand', '1986-06-20', '$argon2id$v=19$m=65536,t=10,p=1$K71VLc5pzTTiH+IDziXhEg$5VO2w1Iejk76IpZT8rTj6f0QIHXBI4MIWuUDD0FBses', 2);
INSERT INTO bds.user (first_name, last_name, username, date_of_birth, password_hash, role_id) VALUES ('Ava', 'Clark', 'avaclark', '1994-01-08', '$argon2id$v=19$m=65536,t=10,p=1$bMc5Wfoxsf9ycK0Cb13cuw$pHKdNyQ4T0TuJ4JrYPP/BEbJfR1pO/i0Hg4hmxV27J0', 3);
INSERT INTO bds.user (first_name, last_name, username, date_of_birth, password_hash, role_id) VALUES ('Mason', 'Walker', 'masonw', '1989-12-02', '$argon2id$v=19$m=65536,t=10,p=1$Aq8N0D8+a27zrKK45oa50g$J7O9bx8lEVcjA3/N1ZqDZxRFcBNi4NrdxEuSMDDTGNs', 3);
INSERT INTO bds.user (first_name, last_name, username, date_of_birth, password_hash, role_id) VALUES ('Harper', 'Evans', 'harper123', '1996-08-14', '$argon2id$v=19$m=65536,t=10,p=1$V3DY1l6qPQZeYf9W/mLjUA$gHkPibnUmQS0kUgT9HKn/gzr8Q+nBSUaj50Ut+WorNA', 3);
INSERT INTO bds.user (first_name, last_name, username, date_of_birth, password_hash, role_id) VALUES ('Logan', 'Turner', 'logant', '1984-10-05', '$argon2id$v=19$m=65536,t=10,p=1$YeDUjl1IjSbBbPIxUt9+ww$AHuYSpbLiKjJIKL6NtnYg0rgSm8f5Z70hfnYDzmYayA', 3);
INSERT INTO bds.user (first_name, last_name, username, date_of_birth, password_hash, role_id) VALUES ('Ella', 'Baker', 'ellab', '1997-06-28', '$argon2id$v=19$m=65536,t=10,p=1$oJ7QP39ev02u0VUG6aiLHQ$sPARPx47LIzHNP/W9zvT+NjAUPOcT4XWpLFajdNl6aE', 3);
INSERT INTO bds.user (first_name, last_name, username, date_of_birth, password_hash, role_id) VALUES ('Carter', 'Perez', 'carterp', '1983-09-03', '$argon2id$v=19$m=65536,t=10,p=1$dmpLBGCs0HtqW1Vonlf8nQ$lyK81UAIZ/YsUMPTWex4QLq2F9tcGFLigbRSZplsFHw', 3);
INSERT INTO bds.user (first_name, last_name, username, date_of_birth, password_hash, role_id) VALUES ('Grace', 'Ward', 'graceward', '1998-11-17', '$argon2id$v=19$m=65536,t=10,p=1$BMPOi4h8/iSn2z/gASFoqQ$MSoOTC72KMZojtpybPPzIpOO7XA55gywduY3Z6Ck+aQ', 2);
INSERT INTO bds.user (first_name, last_name, username, date_of_birth, password_hash, role_id) VALUES ('Lucas', 'Hayes', 'lucash', '1982-12-09', '$argon2id$v=19$m=65536,t=10,p=1$tUm+1lWKmLyQMNJiPbcVww$Vr7PDdRn7gxchLO9xZwdHXl/mMh0YvfFDpe49iF5MGY', 2);
INSERT INTO bds.user (first_name, last_name, username, date_of_birth, password_hash, role_id) VALUES ('Lily', 'Fisher', 'lilyf', '1999-04-11', '$argon2id$v=19$m=65536,t=10,p=1$cdWcWvngGWLK7dXMk0AoCg$Vcq6W9avLxjw9ibf2+w9QL/aCiIPE9CGOZjv7UzUTX4', 2);
INSERT INTO bds.user (first_name, last_name, username, date_of_birth, password_hash, role_id) VALUES ('Landon', 'Ramirez', 'landonr', '1981-02-01', '$argon2id$v=19$m=65536,t=10,p=1$2N8/8mGVQO7gjgKTnW6jrA$vhBCpgnlRfZM/dtFdpxTHJtJkaTY1mLVPY16MHuRINw', 2);
INSERT INTO bds.user (first_name, last_name, username, date_of_birth, password_hash, role_id) VALUES ('Chloe', 'Barnes', 'chloeb', '2000-07-22', '$argon2id$v=19$m=65536,t=10,p=1$rWs8VckpwMob4KN8cioHeQ$k1lEDPEwovhlons1hRdcOeMHvCY/q3gDDrROvz9wCZk', 3);
INSERT INTO bds.user (first_name, last_name, username, date_of_birth, password_hash, role_id) VALUES ('Alexander', 'Gonzalez', 'alexg', '1980-03-19', '$argon2id$v=19$m=65536,t=10,p=1$gjTyfC6LMdq3+sNDEeQtJA$avtuTYtQFftiSYMxOPWgMjDi6xZhYA87MiALk4HIewg', 2);
INSERT INTO bds.user (first_name, last_name, username, date_of_birth, password_hash, role_id) VALUES ('Aria', 'Cooper', 'ariac', '2001-10-13', '$argon2id$v=19$m=65536,t=10,p=1$ncqoNPsqNLQcBCQAmrU3Aw$0ih3VYK+drir0Tc2C1z5jaRzbnDq6YWR8HCoKHzOeI4', 3);
INSERT INTO bds.user (first_name, last_name, username, date_of_birth, password_hash, role_id) VALUES ('Daniel', 'Gray', 'danielg', '1979-05-07', '$argon2id$v=19$m=65536,t=10,p=1$n5RP9KskRW6ANzZTDgZo3g$GOwrAlkfALn24v6hAKwktaklSASeFk/MSUrjwncMNUU', 3);
INSERT INTO bds.user (first_name, last_name, username, date_of_birth, password_hash, role_id) VALUES ('Jackson', 'Parker', 'jacksonp', '1978-01-16', '$argon2id$v=19$m=65536,t=10,p=1$s+IMJgrrK+GpmQJwmTZfXw$T8VPea3U3N95BCCLzpRL1uoT7hcNBfJLDSv4d9bHQyo', 2);
INSERT INTO bds.user (first_name, last_name, username, date_of_birth, password_hash, role_id) VALUES ('Mia', 'Lopez', 'mial', '2003-12-05', '$argon2id$v=19$m=65536,t=10,p=1$w8As9DmLy7EqXI2TAwvKSw$PS3fFwVNoovHj3fl/hTnRFTbD7Bvv4sAnx9IcpxoeTU', 3);
INSERT INTO bds.user (first_name, last_name, username, date_of_birth, password_hash, role_id) VALUES ('Aiden', 'Price', 'aidenp', '1977-06-26', '$argon2id$v=19$m=65536,t=10,p=1$CLaloxnuD2ypXk5jkAXHDA$gBskMGElOOkNxfSm+gP+mXncFGd9J+u28lQic9UC0pM', 3);
INSERT INTO bds.user (first_name, last_name, username, date_of_birth, password_hash, role_id) VALUES ('Scarlett', 'Stewart', 'scarletts', '2004-08-18', '$argon2id$v=19$m=65536,t=10,p=1$kW/rglsZgOvIldskBbQSiQ$sRPvP+mJ53dKoKxHXqRHlL6Ux0O91bBBMkyO7n7yiDk', 3);
INSERT INTO bds.user (first_name, last_name, username, date_of_birth, password_hash, role_id) VALUES ('Mason', 'Ross', 'masonr', '1976-11-10', '$argon2id$v=19$m=65536,t=10,p=1$PMF9XDHJsmOkYUwqoMX4Ow$2NYXg9GT7uBGHu83dlw43XEjG3lEuKt4akU+ID+FI8M', 3);
INSERT INTO bds.user (first_name, last_name, username, date_of_birth, password_hash, role_id) VALUES ('Zoe', 'Ward', 'zoew', '2005-03-03', '$argon2id$v=19$m=65536,t=10,p=1$HEogaRu9mD2NEjDdLjblog$wghQsmdST8/cmH4m9Mfh0pzDg2UFbdEJcK9AfqAJej0', 5);
INSERT INTO bds.user (first_name, last_name, username, date_of_birth, password_hash, role_id) VALUES ('Elijah', 'Martin', 'elijahm', '1975-07-27', '$argon2id$v=19$m=65536,t=10,p=1$0trzkiniLzCS+JPNAbHcCA$o3AZIhIGYmY9hTl2D4HZA5nelrNBYy3oHGakmQY3fAQ', 3);
INSERT INTO bds.user (first_name, last_name, username, date_of_birth, password_hash, role_id) VALUES ('Avery', 'Fisher', 'averyf', '2006-01-20', '$argon2id$v=19$m=65536,t=10,p=1$HQK/taI/a0Hj56fpwWwrtA$Gh+ZH5t79v4+51Jmj/+41copHXbC4R48++e0qxVCoEo', 5);
INSERT INTO bds.user (first_name, last_name, username, date_of_birth, password_hash, role_id) VALUES ('Amelia', 'Bryant', 'ameliab', '1974-04-14', '$argon2id$v=19$m=65536,t=10,p=1$xzWv9YLQHBUY4Q5E/lKwcw$SDqE1c3ybf3Ko1LdfFNpBqpPEzz8sqXbY4eL/orozN8', 2);
INSERT INTO bds.user (first_name, last_name, username, date_of_birth, password_hash, role_id) VALUES ('Charlotte', 'Grant', 'charlotteg', '2007-06-07', '$argon2id$v=19$m=65536,t=10,p=1$faaDYAgUc1EOY82FS195Lg$UCXquLAFZktsMQoznH3iwTacnCWpy4J2eTA0nHS4eBI', 5);
INSERT INTO bds.user (first_name, last_name, username, date_of_birth, password_hash, role_id) VALUES ('Noah', 'Simmons', 'noahs', '1973-09-30', '$argon2id$v=19$m=65536,t=10,p=1$3N7+PXqnDnyRosDFQnxaOw$/Qw6vOhiw9C2x65DiRpfRWZdQ8lVAZ4AREkkxzZXpCM', 3);
INSERT INTO bds.user (first_name, last_name, username, date_of_birth, password_hash, role_id) VALUES ('Liam', 'Butler', 'liamb', '2008-11-23', '$argon2id$v=19$m=65536,t=10,p=1$Z2STp9spd+/ketgcn5v1Fw$u064C2OXmnnSIvJ5Senzt5eh8pLp+66cU4gQiPgsLqw', 5);
INSERT INTO bds.user (first_name, last_name, username, date_of_birth, password_hash, role_id) VALUES ('Grace', 'Turner', 'gracet', '1972-02-15', '$argon2id$v=19$m=65536,t=10,p=1$piE9+DA3lovRK25thSAgmA$bMF/fnzyuLwwcKezVaKxveXJ7KKFkIv42XJhyglWIlc', 3);
INSERT INTO bds.user (first_name, last_name, username, date_of_birth, password_hash, role_id) VALUES ('Emma', 'Mitchell', 'emmam', '2009-05-10', '$argon2id$v=19$m=65536,t=10,p=1$QHda2qFCoT3S8C2HC3U1rw$c6QtrNs4HQyOC0TknT88ZnBy7QbRa7hQSUfkJ/6YFEc', 5);
INSERT INTO bds.user (first_name, last_name, username, date_of_birth, password_hash, role_id) VALUES ('Lucas', 'Griffin', 'lucasg', '1971-08-04', '$argon2id$v=19$m=65536,t=10,p=1$DaKyRTNtBDZ1+tPi7yxH/g$q3V9rcIoP81TLoSW34jIMoyphuTyqHOQyO15hV3KhS4', 2);
INSERT INTO bds.user (first_name, last_name, username, date_of_birth, password_hash, role_id) VALUES ('Olivia', 'Foster', 'oliviaf', '2010-10-29', '$argon2id$v=19$m=65536,t=10,p=1$Q7pCMQ/qJbGUJC64xNMSJg$NcvrxED0K97QLEVlCB7Ut6PoR4o+ph9Qcu5EHZ3BywY', 5);
INSERT INTO bds.user (first_name, last_name, username, date_of_birth, password_hash, role_id) VALUES ('Ethan', 'Ward', 'ethanw', '1970-01-22', '$argon2id$v=19$m=65536,t=10,p=1$+t/RRh7+Ri/eNW2JsOoThQ$Ze0g6ToK0wrcOYYk1NaGiMg0U1VJ5EmmKs+vmLxxVWY', 3);
INSERT INTO bds.user (first_name, last_name, username, date_of_birth, password_hash, role_id) VALUES ('Sophia', 'Lynch', 'sophial', '2011-04-17', '$argon2id$v=19$m=65536,t=10,p=1$//WYuVwfEjrxKPzTbqBBLw$9KRfq2wqxPDC5Foyw4HWZ1KYMGrGYoMJoRkiAeAQJTs', 5);
INSERT INTO bds.user (first_name, last_name, username, date_of_birth, password_hash, role_id) VALUES ('Lily', 'Roberts', 'lilyr', '2012-06-12', '$argon2id$v=19$m=65536,t=10,p=1$UtYdZ8d+O8hebLOQEJm5Vw$LSNTLRWPR/PvCg69088Oj1Xe2ocxmjptMX+2Y1qFWZo', 5);
INSERT INTO bds.user (first_name, last_name, username, date_of_birth, password_hash, role_id) VALUES ('Aiden', 'Larson', 'aidenl', '1969-09-05', '$argon2id$v=19$m=65536,t=10,p=1$aLOVsFCfHzQidhpKTe/dGQ$I3+yOGgPOhgFgFKj+mAuNWl00i1kC6BUZBnJizEnfUs', 2);
INSERT INTO bds.user (first_name, last_name, username, date_of_birth, password_hash, role_id) VALUES ('Zoe', 'Harrison', 'zoeh', '2013-12-28', '$argon2id$v=19$m=65536,t=10,p=1$AFJ7ytmHrq4I+V5uEn25kA$rg8pdF+DAE55c8sPWTf6+mK5iiixEZDKWF+eiL8efkQ', 5);
INSERT INTO bds.user (first_name, last_name, username, date_of_birth, password_hash, role_id) VALUES ('Elijah', 'Thompson', 'elijaht', '1968-03-21', '$argon2id$v=19$m=65536,t=10,p=1$7UHSMSB3KoA5y3zulc7eIg$yNrjFTyIC/e4QqxmeOLGilMpNu9m2clznh9QmS3ti7w', 3);
INSERT INTO bds.user (first_name, last_name, username, date_of_birth, password_hash, role_id) VALUES ('Ava', 'Phillips', 'avap', '2014-07-14', '$argon2id$v=19$m=65536,t=10,p=1$2RTEwkYSC2bSNwkeSiOdZA$X+oT+OTCx+er1KbZV3bG5O1IaaWc8b3jBnmXQfaDXMQ', 5);
INSERT INTO bds.user (first_name, last_name, username, date_of_birth, password_hash, role_id) VALUES ('Jackson', 'Morgan', 'jackm', '2015-09-17', '$argon2id$v=19$m=65536,t=10,p=1$CVWn2uw5Ax5uDNKYDkNlug$qE97Ocl2vFHmrdbU3Xs6WXNubNQufs2N1meM4BeomR0', 5);
INSERT INTO bds.user (first_name, last_name, username, date_of_birth, password_hash, role_id) VALUES ('Sofia', 'Rogers', 'sofiar', '1967-12-10', '$argon2id$v=19$m=65536,t=10,p=1$1ORI8qG0RBbQrSLOMKJRXQ$ckemT+CGbo2PKPNKNOo3/4nBj2foCZSN3x7TaXf6syQ', 3);
INSERT INTO bds.user (first_name, last_name, username, date_of_birth, password_hash, role_id) VALUES ('Lucas', 'Adams', 'lucasa', '1989-03-05', '$argon2id$v=19$m=65536,t=10,p=1$TjNZlipOtMeqWTJEOQ4SwA$C/ECScRZNmqUWan1mqIF3eATxxTV5hVR5vLJ3GcNp5M', 1);
INSERT INTO bds.user (first_name, last_name, username, date_of_birth, password_hash, role_id) VALUES ('Mia', 'Carter', 'miac', '1966-06-28', '$argon2id$v=19$m=65536,t=10,p=1$+ghkmaKYjEbHosXAt7RN1Q$EcFkjA83xXJqRqo2oN97YiM/BPqHVAfA0s7M+4lcgSQ', 4);
INSERT INTO bds.user (first_name, last_name, username, date_of_birth, password_hash, role_id) VALUES ('Liam', 'Stewart', 'liams', '-10-21', '$argon2id$v=19$m=65536,t=10,p=1$KYBGsLlhhgMwDThfXc/PLg$dcc8PE6IdowP94/wS1qCBKk5Uj5BbVxAwi9U5fpqG3Q', 4);
INSERT INTO bds.user (first_name, last_name, username, date_of_birth, password_hash, role_id) VALUES ('Sophia', 'Miller', 'sophiam', '1991-07-07', '$argon2id$v=19$m=65536,t=10,p=1$PNvVXDt1hWNAs7x7j1Gjzg$Uqp0VD+AYlWdOioMP372IxH5w0IrvX+BJyGdFaDg/YY', 4);
INSERT INTO bds.user (first_name, last_name, username, date_of_birth, password_hash, role_id) VALUES ('Sofia', 'Hill', 'sofiah', '2002-09-29', '$argon2id$v=19$m=65536,t=10,p=1$ObQtcO/GXx+16kKpoUFujA$sZ6m6Nz2MzHb53m03niuaT+tcA1rjazCJPK+3WRnf90', 4);
INSERT INTO bds.user (first_name, last_name, username, date_of_birth, password_hash, role_id) VALUES ('Šimon', 'Bříza', 'sbriza', '1995-09-30', '$argon2id$v=19$m=65536,t=10,p=1$d/U+p7pGUG/rswGnxLQGxw$EcmcZNkYAaEfCCQSL7nJLeaqGFpXDiuBemq/ZqYKQ0U', 3);

-- user_contact
INSERT INTO bds.user_contact (email, phone_number, user_id) VALUES (null, '555-123-7890', 1);
INSERT INTO bds.user_contact (email, phone_number, user_id) VALUES ('gamer_girl42@example.org', '444-234-5678', 2);
INSERT INTO bds.user_contact (email, phone_number, user_id) VALUES ('coding_ninja_01@example.net', '333-345-6789', 3);
INSERT INTO bds.user_contact (email, phone_number, user_id) VALUES ('bookworm_88@example.com', '222-456-7890', 4);
INSERT INTO bds.user_contact (email, phone_number, user_id) VALUES ('music_lover99@example.org', '111-567-8901', 5);
INSERT INTO bds.user_contact (email, phone_number, user_id) VALUES ('traveler_007@example.net', '666-678-9012', 6);
INSERT INTO bds.user_contact (email, phone_number, user_id) VALUES ('foodie_22@example.com', '777-789-0123', 7);
INSERT INTO bds.user_contact (email, phone_number, user_id) VALUES ('fitness_guru_123@example.org', '888-890-1234', 8);
INSERT INTO bds.user_contact (email, phone_number, user_id) VALUES ('tech_geek@example.net', '999-901-2345', 9);
INSERT INTO bds.user_contact (email, phone_number, user_id) VALUES ('coffee_addict@example.com', '123-012-3456', 10);
INSERT INTO bds.user_contact (email, phone_number, user_id) VALUES ('adventure_seeker@example.org', '234-123-4567', 11);
INSERT INTO bds.user_contact (email, phone_number, user_id) VALUES ('daydreamer_42@example.net', '345-234-5678', 12);
INSERT INTO bds.user_contact (email, phone_number, user_id) VALUES ('night_owl@example.com', '456-345-6789', 13);
INSERT INTO bds.user_contact (email, phone_number, user_id) VALUES (null, '567-456-7890', 14);
INSERT INTO bds.user_contact (email, phone_number, user_id) VALUES ('globe_trotter@example.net', '678-567-8901', 15);
INSERT INTO bds.user_contact (email, phone_number, user_id) VALUES ('hiking_enthusiast@example.com', '789-678-9012', 16);
INSERT INTO bds.user_contact (email, phone_number, user_id) VALUES ('coding_guru@example.org', '890-789-0123', 17);
INSERT INTO bds.user_contact (email, phone_number, user_id) VALUES ('coffee_lover_22@example.net', '901-890-1234', 18);
INSERT INTO bds.user_contact (email, phone_number, user_id) VALUES ('star_gazer@example.com', '012-901-2345', 19);
INSERT INTO bds.user_contact (email, phone_number, user_id) VALUES ('travel_bug_88@example.org', '123-112-3456', 20);
INSERT INTO bds.user_contact (email, phone_number, user_id) VALUES ('coding_whiz@example.net', '234-223-4567', 21);
INSERT INTO bds.user_contact (email, phone_number, user_id) VALUES ('food_explorer@example.com', '345-334-5678', 22);
INSERT INTO bds.user_contact (email, phone_number, user_id) VALUES ('yoga_master@example.org', '456-445-6789', 23);
INSERT INTO bds.user_contact (email, phone_number, user_id) VALUES ('skydiver_007@example.net', '567-556-7890', 24);
INSERT INTO bds.user_contact (email, phone_number, user_id) VALUES ('art_lover_123@example.com', '678-667-8901', 25);
INSERT INTO bds.user_contact (email, phone_number, user_id) VALUES ('movie_buff@example.org', '789-778-9012', 26);
INSERT INTO bds.user_contact (email, phone_number, user_id) VALUES ('gaming_enthusiast@example.net', '890-889-0123', 27);
INSERT INTO bds.user_contact (email, phone_number, user_id) VALUES (null, '901-900-1234', 28);
INSERT INTO bds.user_contact (email, phone_number, user_id) VALUES ('fitness_freak@example.org', '012-011-2345', 29);
INSERT INTO bds.user_contact (email, phone_number, user_id) VALUES ('nature_lover_22@example.net', '123-122-3456', 30);
INSERT INTO bds.user_contact (email, phone_number, user_id) VALUES ('photography_lover@example.com', '234-233-4567', 31);
INSERT INTO bds.user_contact (email, phone_number, user_id) VALUES (null, '345-344-5678', 32);
INSERT INTO bds.user_contact (email, phone_number, user_id) VALUES ('dreamer_42@example.net', '456-455-6789', 33);
INSERT INTO bds.user_contact (email, phone_number, user_id) VALUES ('adventure_seeker_007@example.com', '567-566-7890', 34);
INSERT INTO bds.user_contact (email, phone_number, user_id) VALUES ('coding_nerd_123@example.org', '678-677-8901', 35);
INSERT INTO bds.user_contact (email, phone_number, user_id) VALUES ('travel_enthusiast@example.com', '111-111-2222', 36);
INSERT INTO bds.user_contact (email, phone_number, user_id) VALUES ('coding_mastermind@example.org', '222-222-3333', 37);
INSERT INTO bds.user_contact (email, phone_number, user_id) VALUES ('gourmet_cook@example.net', '333-333-4444', 38);
INSERT INTO bds.user_contact (email, phone_number, user_id) VALUES (null, '444-444-5555', 39);
INSERT INTO bds.user_contact (email, phone_number, user_id) VALUES ('music_maestro@example.org', '555-555-6666', 40);
INSERT INTO bds.user_contact (email, phone_number, user_id) VALUES ('book_lover@example.net', '666-666-7777', 41);
INSERT INTO bds.user_contact (email, phone_number, user_id) VALUES ('nature_observer@example.com', '777-777-8888', 42);
INSERT INTO bds.user_contact (email, phone_number, user_id) VALUES ('coding_whizkid@example.org', '888-888-9999', 43);
INSERT INTO bds.user_contact (email, phone_number, user_id) VALUES ('adventure_seeker_22@example.net', '999-999-0000', 44);
INSERT INTO bds.user_contact (email, phone_number, user_id) VALUES ('coffee_addict_22@example.com', '000-000-1111', 45);
INSERT INTO bds.user_contact (email, phone_number, user_id) VALUES (null, '111-111-2222', 46);
INSERT INTO bds.user_contact (email, phone_number, user_id) VALUES ('music_lover_22@example.net', '222-222-3333', 47);
INSERT INTO bds.user_contact (email, phone_number, user_id) VALUES ('bookworm_22@example.com', '333-333-4444', 48);
INSERT INTO bds.user_contact (email, phone_number, user_id) VALUES ('coding_pro_22@example.org', '444-444-5555', 49);
INSERT INTO bds.user_contact (email, phone_number, user_id) VALUES ('traveler_22@example.net', '555-555-6666', 50);
INSERT INTO bds.user_contact (email, phone_number, user_id) VALUES ('art_enthusiast_22@example.com', '666-666-7777', 51);
INSERT INTO bds.user_contact (email, phone_number, user_id) VALUES (null, '777-777-8888', 52);

-- loaned_book
INSERT INTO bds.loaned_book (user_id, physical_book_id, is_returned, issue_date, due_date, library_id) VALUES (26, 34, True, '2023-09-01', '2023-10-01', 2);
INSERT INTO bds.loaned_book (user_id, physical_book_id, is_returned, issue_date, due_date, library_id) VALUES (26, 32, True, '2023-09-01', '2023-10-01', 2);
INSERT INTO bds.loaned_book (user_id, physical_book_id, is_returned, issue_date, due_date, library_id) VALUES (25, 1, True, '2023-09-03', '2023-10-03', 1);
INSERT INTO bds.loaned_book (user_id, physical_book_id, is_returned, issue_date, due_date, library_id) VALUES (14, 4, True, '2023-09-11', '2023-10-11', 3);
INSERT INTO bds.loaned_book (user_id, physical_book_id, is_returned, issue_date, due_date, library_id) VALUES (14, 5, True, '2023-09-11', '2023-10-11', 3);
INSERT INTO bds.loaned_book (user_id, physical_book_id, is_returned, issue_date, due_date, library_id) VALUES (14, 6, True, '2023-09-11', '2023-10-11', 3);
INSERT INTO bds.loaned_book (user_id, physical_book_id, is_returned, issue_date, due_date, library_id) VALUES (24, 10, False, '2023-09-16', '2023-10-16', 5);
INSERT INTO bds.loaned_book (user_id, physical_book_id, is_returned, issue_date, due_date, library_id) VALUES (31, 11, True, '2023-09-21', '2023-10-21', 2);
INSERT INTO bds.loaned_book (user_id, physical_book_id, is_returned, issue_date, due_date, library_id) VALUES (31, 15, True, '2023-09-21', '2023-10-21', 2);
INSERT INTO bds.loaned_book (user_id, physical_book_id, is_returned, issue_date, due_date, library_id) VALUES (31, 9, True, '2023-09-21', '2023-10-21', 2);
INSERT INTO bds.loaned_book (user_id, physical_book_id, is_returned, issue_date, due_date, library_id) VALUES (12, 41, True, '2023-10-01', '2023-11-01', 6);
INSERT INTO bds.loaned_book (user_id, physical_book_id, is_returned, issue_date, due_date, library_id) VALUES (13, 31, False, '2023-10-12', '2023-11-12', 7);
INSERT INTO bds.loaned_book (user_id, physical_book_id, is_returned, issue_date, due_date, library_id) VALUES (34, 1, False, '2023-10-15', '2023-11-15', 8);
INSERT INTO bds.loaned_book (user_id, physical_book_id, is_returned, issue_date, due_date, library_id) VALUES (41, 34, False, '2023-10-16', '2023-11-16', 3);

-- book_request
INSERT INTO bds.book_request (ISBN, title, user_id) VALUES ('978-112-233-445-5', 'Into the Unknown', 6);
INSERT INTO bds.book_request (ISBN, title, user_id) VALUES ('978-998-877-665-4', 'The Last Frontier', 14);
INSERT INTO bds.book_request (ISBN, title, user_id) VALUES ('978-667-788-990-0', 'Under the Moonlight', 34);
INSERT INTO bds.book_request (ISBN, title, user_id) VALUES ('978-554-433-221-1', 'Whispers in the Dark', 22);
INSERT INTO bds.book_request (ISBN, title, user_id) VALUES ('978-443-322-110-0', 'A Tale of Two Worlds', 14);
INSERT INTO bds.book_request (ISBN, title, user_id) VALUES ('978-778-899-001-1', 'The Enchanted Forest', 35);
INSERT INTO bds.book_request (ISBN, title, user_id) VALUES ('978-112-223-435-5', 'Through the Looking Glass', 4);
INSERT INTO bds.book_request (ISBN, title, user_id) VALUES ('978-334-455-667-7', 'Beneath the Surface', 7);
INSERT INTO bds.book_request (ISBN, title, user_id) VALUES ('978-112-133-545-5', 'The Secret Garden', 4);
INSERT INTO bds.book_request (ISBN, title, user_id) VALUES ('978-665-544-332-2', 'The Lost City', 36);

-- access_log
INSERT INTO bds.access_log ("timestamp", user_id, ip) VALUES ('2023-09-01 17:56:13', 39, '192.168.1.23');
INSERT INTO bds.access_log ("timestamp", user_id, ip) VALUES ('2023-09-02 18:50:28', 6, '192.168.1.18');
INSERT INTO bds.access_log ("timestamp", user_id, ip) VALUES ('2023-09-06 19:47:55', 14, '192.168.1.18');
INSERT INTO bds.access_log ("timestamp", user_id, ip) VALUES ('2023-09-07 22:05:18', 9, '192.168.1.11');
INSERT INTO bds.access_log ("timestamp", user_id, ip) VALUES ('2023-09-08 11:30:59', 18, '192.168.1.21');
INSERT INTO bds.access_log ("timestamp", user_id, ip) VALUES ('2023-09-11 13:28:40', 16, '192.168.1.11');
INSERT INTO bds.access_log ("timestamp", user_id, ip) VALUES ('2023-09-14 05:22:47', 29, '192.168.1.23');
INSERT INTO bds.access_log ("timestamp", user_id, ip) VALUES ('2023-09-14 11:17:55', 7, '192.168.1.20');
INSERT INTO bds.access_log ("timestamp", user_id, ip) VALUES ('2023-09-17 22:40:02', 16, '192.168.1.19');
INSERT INTO bds.access_log ("timestamp", user_id, ip) VALUES ('2023-09-19 07:11:56', 10, '192.168.1.11');
INSERT INTO bds.access_log ("timestamp", user_id, ip) VALUES ('2023-09-23 10:15:31', 15, '192.168.1.18');
INSERT INTO bds.access_log ("timestamp", user_id, ip) VALUES ('2023-09-25 03:50:27', 27, '192.168.1.13');
INSERT INTO bds.access_log ("timestamp", user_id, ip) VALUES ('2023-09-29 04:05:44', 17, '192.168.1.20');
INSERT INTO bds.access_log ("timestamp", user_id, ip) VALUES ('2023-09-29 16:40:33', 8, '192.168.1.20');
INSERT INTO bds.access_log ("timestamp", user_id, ip) VALUES ('2023-10-04 13:14:37', 25, '192.168.1.25');
INSERT INTO bds.access_log ("timestamp", user_id, ip) VALUES ('2023-10-12 16:38:09', 11, '192.168.1.16');
INSERT INTO bds.access_log ("timestamp", user_id, ip) VALUES ('2023-10-15 09:35:42', 5, '192.168.1.6');
INSERT INTO bds.access_log ("timestamp", user_id, ip) VALUES ('2023-10-19 14:20:47', 13, '192.168.1.16');
INSERT INTO bds.access_log ("timestamp", user_id, ip) VALUES ('2023-10-20 20:40:59', 34, '192.168.1.26');
INSERT INTO bds.access_log ("timestamp", user_id, ip) VALUES ('2023-10-25 08:55:33', 12, '192.168.1.15');
INSERT INTO bds.access_log ("timestamp", user_id, ip) VALUES ('2023-10-28 09:48:58', 46, '192.168.1.25');
INSERT INTO bds.access_log ("timestamp", user_id, ip) VALUES ('2023-10-28 14:22:10', 4, '192.168.1.5');
INSERT INTO bds.access_log (user_id, ip) VALUES (32, '192.168.1.35');
INSERT INTO bds.access_log (user_id, ip) VALUES (37, '192.168.1.35');
